version: "3.8"
services:
    nginx:
        container_name: frontend_webauthn_nginx
        image: frontend-nginx
        build:
            context: ./
            dockerfile: Dockerfile.multi
        expose:
            - "80"
            - "443"
        ports:
            - "8800:80"
            - "4433:443"
        networks:
            - myNetwork
networks:
    myNetwork:
        name: frontend_webauthn
